#!/usr/bin/python
#import Bio
#print(Bio.__version__)
#from Bio.Seq import Seq
#from Bio import SeqIO
#input_file= input('Enter fasta file=')
#fasta_sequences = SeqIO.parse(open(input_file),'fasta')
#print(input_file)

name_list=[]
line_list=[]
readnames=[]
line_list1=[]
seq=[]
refseq=[]
refnames=[]

#FASTA1=input('enter reference file:')
vlsE='GAGGGGGCTATTAAGGAAGTTAGCGAGTTGTTGGATAAGCTGGTAAAAGCT---GTAAAGACAGCTGAGGGGGCTTCAAGTGGTACTGCTGCAATTGGAGAAGTTGTGGCTGATGCTGATGCTGCAAAGGTTGCTGATAAGGCGAGTGTGAAGGGGATTGCTAAGGGGATAAAGGAGATTGTTGAAGCTGCTGGGGGG---AGTGAAAAGCTGAAAGCTGTTGCTGCTGCTAAAGGGGAGAATAATAAAGGGGCAGGGAAGTTGTTTGGGAAGGCTGGTGCTGCTGCTCAT------GGGGACAGTGAGGCTGCTAGCAAGGCGGCTGGTGCTGTTAGTGCTGTT---AGTGGGGAGCAGATATTAAGTGCGATTGTTACGGCTGCTGATGCG------------GCTGAGCAGGATGGAAAGAAGCCTGAGGAGGCTAAAAATCCGATTGCTGCTGCTATTGGGGATAAAGATGGGGGT------GCGGAGTTTGGTCAGGATGAGATGAAGAAGGATGATCAGATTGCTGCTGCTATTGCTTTGAGGGGGATGGCTAAGGATGGAAAGTTTGCTGTGAAG---GAT---GGTGAGAAAGAGAAGGCT'
vls3='GAGGGGGCTATTAAGGGAGCTGGCGAGTTGTTGGATAAGCTGGTAAAAGCT---GTAAAGACAGCTGAGGGGGCTTCAAGTGGTACTGCTGCAATTGGAGAAGTTGTGGCTGATGATAATGCTGCGAAGGTTGCTGATAAGGCGAGTGTGAAGGGGATTGCTAAGGGGATAAAGGAGATTGTTGAAGCTGCTGGGGGG---AGTAAAAAGCTGAAA---GTTGCTGCTGCTAAA---GAGGGCAATGAAAAGGCAGGGAAGTTGTTTGGGAAAGTTGATGCTGCT---CATGCT---GGGGACAGTGAGGCTGCTAGCAAGGCGGCTGGTGCTGTTAGTGCTGTT---AGTGGGGAGCAGATATTAAGTGCGATTGTTAAGGCTGCTGGTGCGGCTGCT------GGTGATCAGGAGGGAAAGAAGCCTGGGGATGCTAAAAATCCGATTGCTGCTGCTATTGGGAAGGGTGATGCGGAGAATGGTGCGGAGTTTAATCATGATGGGATGAAGAAGGATGATCAGATTGCTGCTGCTATTGCTTTGAGGGGGATGGCTAAGGATGGAAAGTTTGCTGTGAAGAGTGGTGGTGGTGAGAAAGGGAAGGCT'
consensus='GAGGGGGCTATTAAGGAAGTTAGCGAGTTGTTGGATAAGCTGGTAAAAGCTOOOGTAAAGACAGCTGAGGGGGCTTCAAGTGGTACTGCTGCAATTGGAGAAGTTGTGGCTGATGCTGATGCTGCAAAGGTTGCTGATAAGGCGAGTGTGAAGGGGATTGCTAAGGGGATAAAGGAGATTGTTGAAGCTGCTGGGGGGOOOAGT	GAA	AAG	CTG	AAA	GCT	GTT	GCT	GCT	GCT	AAA	GGG	GAG	AAT	AAT	AAA	GGG	GCA	GGG	AAG	TTG	TTT	GGG	AAG	GCT	GGT	GCT	GCT	GCT	CAT	OOO	OOO	GGG	GAC	AGT	GAG	GCT	GCT	AGC	AAG	GCG	GCT	GGT	GCT	GTT	AGT	GCT	GTT	OOO	AGT	GGG	GAG	CAG	ATA	TTA	AGT	GCG	ATT	GTT	ACG	GCT	GCT	GAT	GCG	OOO	OOO	OOO	OOO	GCT	GAG	CAG	GAT	GGA	AAG	AAG	CCT	GAG	GAG	GCT	AAA	AAT	CCG	ATT	GCT	GCT	GCT	ATT	GGG	GAT	AAA	GAT	GGG	GGT	OOO	OOO	GCG	GAG	TTT	GGT	CAG	GAT	GAG	ATG	AAG	AAG	GAT	GAT	CAG	ATT	GCT	GCT	GCT	ATT	GCT	TTG	AGG	GGG	ATG	GCT	AAG	GAT	GGA	AAG	TTT	GCT	GTG	AAG	OOO	GAT	OOO	GGT	GAG	AAA	GAG	AAG	GCT'
FASTA=input('enter read file:')

in_file=open(FASTA, 'r')


#in_file1=open(FASTA1, 'r')


for line in in_file:
  line=line.strip()

  line_list.append(line)
readnames=line_list[::2]        #list of the read headers
seq=line_list[1::2]         #list of sequences only


#for line1 in in_file1:
 # line1=line1.strip()
 # line_list1.append(line1) 
#refseq=line_list1[1::2]
#refnames=line_list1[::2]


#print(seq[0][0],seq[0][1],seq[0][2],seq[0][379],seq[1][387])

print(seq[0][0])
#for i in seq[0]:
 # if j in i:
    #if i==


#print(readnames)
#print(len(readnames))
#print("hi")
print(seq)
#print(len(seq))
#for i in 
  

      
#print(line_list[0])
#print(line_list[1])

 
L1=[]
L3=[]
  
for i in range(0,len(seq)):
  for j in range (0, len(seq[i])):
    if seq[i][j]==vlsE[j]:
      L1.append(seq[i][j])
      
    if seq[i][j]==vls3[j]:
      L3.append(seq[i][j])
    else:
       L1.append(''.join(L1))
       L3.append(''.join(L3)
 #     if seq[i][j]==consensus[i][j]
        
